server:
    port: 8080
    servlet:
        contextPath: /api
spring:
    profiles.actives: "default"
    application:
        name: StatisticalRestService
    jpa:
        #database: POSTGRESQL
        databasePlatform: "org.hibernate.dialect.PostgreSQL9Dialect"
        show-sql: true
        hibernate:
            ddl-auto: create-drop
            jdbc:
                lob:
                    non_contextual_creation: true
        properties.hibernate.temp.use_jdbc_metadata_defaults: false
    datasource:
        platform: postgresql
        url: jdbc:postgresql://localhost:5432/StatisticalRestService
        username: statEntityUser
        password: test123
        driverClassName: org.postgresql.Driver
project:
    version: '@project.version@'
info:
    app:
        version: '@project.version@'